name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

          
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Access MAPBOX_DOWNLOADS_TOKEN
      env:
        MAPBOX_DOWNLOADS_TOKEN: ${{secrets.MAPBOX_DOWNLOADS_TOKEN}}
      run: echo project.ext.MAPBOX_DOWNLOADS_TOKEN=\"${{secrets.MAPBOX_DOWNLOADS_TOKEN}}\" > ./local.properties

    - name: Access SENTRY_TOKEN
      env:
        SENTRY_TOKEN: ${{secrets.SENTRY_TOKEN}}
      run: echo "[auth]\ntoken=\"${{secrets.SENTRY_TOKEN}}\"" > ~/.sentryclirc

    - name: Build with Gradle
      run: ./gradlew build
